Feat/reuseComponent/#15
ASAP-as-soon-as-possible/ASAP_Client pull request #18
Opened 2023-07-06 15:44 UTC by Chanwoo-Jeong

### ✨ 해당 이슈 번호 ✨
#15 

### todo 
- [ ] 현재 나온 GUI 컴포넌트 제일 많이 쓸거같은거 만들기

## 📌 내가 알게 된 부분
- input blur 되기전 함수 실행되어야 한다..
<img width="800" alt="image" src="https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/91375979/50b76f79-f90f-4a19-8f40-c27845407979">

## 📌 질문할 부분 
- stylelint prettier 충돌.... 해결!

## 📌스크린샷

<img width="754" alt="image" src="https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/91375979/4cf41748-03fe-4419-b394-d8bc3e0eee92">

1. TextInput 사용법

<img width="754" alt="image" src="https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/91375979/40f4dbe7-5e8a-4750-b558-9a1dfdfb5898">

2. Text 사용법
<img width="754" alt="image" src="https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/91375979/ac00c5ba-f369-4991-9d58-cd8e4e625b86">

3. Button 사용법
<img width="754" alt="image" src="https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/91375979/6ad7f552-1c91-4f32-a94d-cd2756a68337">

2023-07-07 03:12 UTC, eastlaw80 commented
와우,,,,,진짜 깔끔하게 예시와 사용법까지....고생했어..!!!!

2023-07-07 03:15 UTC, eastlaw80 commented on src/components/atomComponents/Text.tsx
> +      return '';
와 이렇게 해놔서 컴포넌트에 프로퍼티로 이름 넣으면 바로 스타일이 적용되는구나,,,최고다

2023-07-07 11:55 UTC, ljh0608 commented on src/components/atomComponents/Text.tsx
> +      return '';
오우 편리하게 해놔서 너무 좋다!

2023-07-07 12:44 UTC, simeunseo requested changes
진짜 무친 속도! 최고야! 고생했어!!
switch문으로 style 반환해서 쓰는거 처음봐서 넘나 신기하네...

근데 이슈가 하나 있습니다!
보는데 피그마에서 보는거랑 폰트 굵기가 묘하게 다른것 같아서 확인해보니까,
theme에서 폰트가 'Pretendard Variable'이 아니라 'Pretendard'로 되어있어서 font-weight 속성이 안먹는것같아요
그래서 theme에서 전부 'Pretendard Variable'로 바꾸니까 굵기가 달라지더라구요
![image](https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/55528304/523fcc19-2160-4a99-932d-e8efa653831b)
![image](https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/55528304/551ae501-27a8-4962-9c2f-729b18e22483)
첫번째가 Pretendard (기존), 두번째가 Pretendard-Variable(제가 바꿔본것)
차이 보이시나요??

결론은 theme.ts에서 Pretendard를 Pretendard Variable로 바꿔서 같이 머지해주시면 좋을거같아요!

2023-07-07 12:44 UTC, simeunseo commented on src/components/atomComponents/TextInput.tsx
> +const Wrapper = styled.div``
요건 지웁시다!! 가 아니라.... 아 이거 전에 매머드카페에서 얘기나왔던거같은데, 스타일이 없는 태그도 styledComponent로 해야되냐구 내가 물었었는데 그런건 그냥 일반 태그로 쓰기로 하지 않았나? 잘 기억이 안나네....
그냥 어차피 스타일이 필요하지 않으면 Wrapper 컴포넌트 자체를 안넣어도 되는거아닌가?!
가 아니라 이건근데 어차피 공통컴포넌트 보여주기용 페이지니까 신경 안써도 되겠구나 ㅋㅋㅋㅋㅋ ㅈㅅ
이상 심은서의 생각타래였습니다~

2023-07-07 13:05 UTC, simeunseo commented on src/components/atomComponents/TextInput.tsx
> +            iserror={value?.length > 15}
boolean prop 대신 cs를 사용하자고 했었는데 흠 이부분 어떻게 생각하시나요? 컨벤션 수정하고 편한대로 하는게 나을지, 컨벤션 지키는게 좋을지.. cs 쓰는것도 쓰다보면 익숙해지긴할텐뎅

2023-07-07 13:05 UTC, simeunseo commented on src/components/atomComponents/Text.tsx
> +
styledComponent에서 사용하는 prop은 transient prop($font)을 사용하자는게 컨벤션이었는데 이것도 아까 cs 사용과 마찬가지로 어떻게 생각하시는지 궁금합니다

2023-07-07 13:49 UTC, Chanwoo-Jeong commented on src/components/atomComponents/TextInput.tsx
> +`;
ㅋㅋㅋㅋㅋㅋㅋㅋ 디테일 왜 놓칠까... 감사링

2023-07-07 13:52 UTC, Chanwoo-Jeong commented on src/components/atomComponents/TextInput.tsx
> +const Wrapper = styled.div``
스타일이 필요없는건 맞는데 최상단을 감싸는 Wrapper 는 필요하다고 생각해!

컨벤션이 Wrapper 부터 시작되는데 최상단에 스타일이 들어가지 않는다고 하더라도 Wrapper 없으면 안된다고 생각해서!
그리고 최상단에는 결국 언제가 style이 들어갈거라  생각해서 최상단 Wrapper 는 무조건 있어야 한다고 생각했어!

그 하위 자식들은 그냥 div 나 span 으로 쓰는게 맞지만! 무언갈 감싸는 중요한 Wrapper 라면 style 이 없더라도
Wrapper -> Seciton -> Container -> box 순으로!

2023-07-07 13:53 UTC, Chanwoo-Jeong commented on src/components/atomComponents/TextInput.tsx
> +            iserror={value?.length > 15}
개인적으로 className 을 건드는게 맞는지 아직 의문이 들어요,,,, 그리고 prop 이 조금 더 가독성이 좋다고 생각하기도 하구요..! 논의해봅시다!

2023-07-07 13:53 UTC, Chanwoo-Jeong commented on src/components/atomComponents/Text.tsx
> +
윗 답변과 같이 논의 필요!

2023-07-07 13:54 UTC, Chanwoo-Jeong commented on src/components/atomComponents/Text.tsx
> +
추가로 Theme 건드는건 동헌이 파트라 일단 theme  을 건들지 않는 상태에서 작업했어!

2023-07-08 06:10 UTC, ljh0608 reviewed
고생하셨습니다 찬부장님

2023-07-08 06:10 UTC, ljh0608 commented on src/components/atomComponents/Button.tsx
> +        return '';
P3) 버튼 네이밍만 봤을 때 아직 무슨 버튼인지 모르겠는데 혹시 구분할 수 있는 좋은 방법이 있을까요?  ( tertiary, second보다 더 직관적인 네이밍을 사용하거나 주석이 필요할 것 같다는 생각입니다)

2023-07-08 06:32 UTC, Chanwoo-Jeong commented on src/components/atomComponents/Button.tsx
> +        return '';
요거 그 GUI 가이드라인! 이름을 따서 만든거라 GUI 보면 될것같아!

2023-07-08 14:25 UTC, merged