Feat/reuseComponentFix/#22
ASAP-as-soon-as-possible/ASAP_Client pull request #23
Opened 2023-07-08 14:59 UTC by Chanwoo-Jeong

### ✨ 해당 이슈 번호 ✨
#22 

### todo 
- [ ] Text Component 에 Color 프롭 넘겨주는거 까먹어서 추가하기

## 📌 내가 알게 된 부분
- 찬우는 바보 텍스트 색이 바뀔거라는걸 왜 몰라?
 

## 📌 질문할 부분 
- X

## 📌스크린샷
<img width="800" alt="image" src="https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/91375979/93a4fced-6d2c-4617-96b4-f183ec2e887d">

🎯Text Prop 으로 color 를 전달할 수 있게 되었습니다! map 리팩토링은 덤!

2023-07-08 17:36 UTC, eastlaw80 commented
Pn5
확인했습니다~~!~!~!

2023-07-08 19:02 UTC, ljh0608 requested changes
styled-components/macro사용과
DOM에서 boolean props사용 warnings를 고쳐주세요!

2023-07-09 01:16 UTC, simeunseo commented
LGTM

2023-07-11 04:02 UTC, Chanwoo-Jeong commented on src/components/moleculesComponents/TitleComponents.tsx
> +import { styled } from 'styled-components';
적용

2023-07-11 04:03 UTC, Chanwoo-Jeong commented on src/components/atomComponents/TextInput.tsx
>  import { styled } from 'styled-components';
적용

2023-07-11 04:03 UTC, merged