Feat/moleculesComponent/#21
ASAP-as-soon-as-possible/ASAP_Client pull request #25
Opened 2023-07-09 10:13 UTC by Chanwoo-Jeong

### ✨ 해당 이슈 번호 ✨
#21 

### todo 
- [ ] textArea reuseComponent 제작
- [ ] TitleComponent 제작
- [ ] useFunnel 을 이용한 앞쪽 파트 view Test 제작

## 📌 내가 알게 된 부분
- useFunnel 이라는 개념을 이용하여 데이터를 굳이 전역으로 저장하지 않고 한개의 컴포넌트에서 상태관리로 처리하는 방법
- dom 은 boolean 값을 뱉어 string 좋아 
- childeren 에 { } 문법을 쓸때 뒤에 띄어쓰기가 있으면 string[ ] 으로 인식해버림 조심하세요!
- 
<img width="800" alt="image" src="https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/91375979/5a34b7b0-c20e-4e43-a850-9bca05de6bc5">

## 📌 질문할 부분 
- 있으면 추가할게요.

## 📌스크린샷
1. TextAreaInput 공통 컴포넌트 제작
<img width="400" alt="image" src="https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/91375979/7d1c45a5-ec51-4b45-a891-d7e6f1b45266">
<img width="400" alt="image" src="https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/91375979/6dfba316-8188-49fd-9ed8-f955da7d9267">
<img width="800" alt="image" src="https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/91375979/f41ad4b1-64e8-4a88-994a-842b2dcd53c6">

2. useFunnel 을 통한 앞쪽 뷰 작업 테스팅
https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/91375979/76251782-e140-4f7b-b5b8-0d10009acbd9

2023-07-09 11:15 UTC, simeunseo requested changes
1. Hooks 폴더 이름 hooks로 바꿔주세요!! 근데 폴더 이름 바꾸는거 git이 인식 못해서 [여기](https://velog.io/@gidskql6671/Git-%ED%8C%8C%EC%9D%BC-%EB%B0%8F-%ED%8F%B4%EB%8D%94%EB%AA%85-%EB%8C%80%EC%86%8C%EB%AC%B8%EC%9E%90-%EB%B3%80%EA%B2%BD)서 알려주는 대로 해야 반영되더라구요!!
2. Funnel 관련 내용은 moleculesComponent와는 좀 분리가 되어야할것같은데 같이 묶여있어서 쪼금 헷갈리는것같아요 그냥 테스트 해보느라 그런거죠!? 나중에 이런거는 분리해서 이슈 파도 좋을듯..??

useFunnel 진짜 너무 스마트 하다!!!!!!!!!!!!! 멋찌다!!!!!1!!!!!!!!!!!1!!!!!!!!!!1 어떢꼐이렇게 빨리공부해서 적용해?

2023-07-09 11:15 UTC, simeunseo commented on src/components/moleculesComponents/Header.tsx
> +  setStep: Dispatch<SetStateAction<number>>;
혹시 여기서 Dispatch가 무엇인가요...? (몰라서물음) 그냥 setState함수에 대해 type을 지정하기 위해 쓰이는건가요?

2023-07-09 11:15 UTC, simeunseo commented on src/pages/ViewTesting.tsx
> +      </ViewTestingWrapper>
이런식으로 간다면 이걸 또 공통 레이아웃으로 빼야하는걸까요?!

2023-07-09 13:34 UTC, Chanwoo-Jeong commented on src/components/moleculesComponents/Header.tsx
> +  setStep: Dispatch<SetStateAction<number>>;
옙 맞습니당!

2023-07-09 13:34 UTC, Chanwoo-Jeong commented on src/components/atomComponents/TextAreaInput.tsx
> +      <StyledTextArea placeholder={placeholder} value={value} onChange={textOnChange} />
최곱니다.!!!!!! maxlength

2023-07-09 13:35 UTC, Chanwoo-Jeong commented on src/pages/ViewTesting.tsx
> +      </ViewTestingWrapper>
음 일단 moleculesComponent 에 넣어두긴 했는데 앞쪽 뷰만 useFunnel 폴더를 하나 만들까 생각중이기는 합니다..! 월요일날 이야기해보아요

맞아 아래쪽을 이제 공통레이아웃으로 다시 분리해서 각 스텝마다 렌더링 될 수 있도록 해야할것같아!

2023-07-10 11:05 UTC, ljh0608 requested changes
읽기 쉽고 나이스한 코드입니다 감사링~

2023-07-11 08:59 UTC, eastlaw80 commented
P5) 긴긴 커밋을 읽는 과정을 거쳐왔습니다,,,의문이 들만한 점들은 은서하고 재훈이형이 다 해준거 같아요! 고생하셨습니다,,!

2023-07-12 07:51 UTC, merged