Fix/#256/possible time page change error
ASAP-as-soon-as-possible/ASAP_Client pull request #259
Opened 2024-07-09 18:15 UTC by ljh0608

## 🌀 해당 이슈 번호
#256 
- close #

## 🔹 어떤 것을 변경했나요?

- [ ] 가능시간 입력 후 우선순위 로직에서 뒤로가기시 상태 변경에서 잘못된 값을 불러오는 에러를 수정
- [ ] 서버에 우선순위에 따라 가중치를 주는 것으로 코드 수정 (1순위= priority : 3)
- [ ] 가능시간 입력 api request 형식 변경 (id값이나 요일 값 제외)
- [ ] 빌드 에러 수정 (폴더명 카멜케이스로 변경)

## 🔹 어떻게 구현했나요?
우선순위를 수정하는 로직은 1순위를 선택할 때 
1. 기존에 1순위가 있으면 0으로 초기화한다.
2. 그 후 해당 시간을 1순위 (priority:3)으로 값을 변경한다.
인데 1의 과정에서 중첩객체가 객체 배열로 변경되고 이 과정에서 key값이 index값으로 설정되는 오류가 발생함
따라서 해당 로직을 수정해주었습니다.

## 🔹 PR 포인트를 알려주세요!
기존에 enties, fromEntries로직에서 에러가 있는것을 발견하고 reduce메소드를 사용해 구현하였습니다. 
 아래 로직은 크게 두가지로 나뉩니다.
1.  이미 해당 순위가 선택되어있으면 0으로 초기화
2. priority 값 적용
```
    setSelectedSlots((prev: SelectedSlotType) => {
      const updatedSelectedSlots = Object.entries(prev).reduce(
        (acc, [key, value]) => {
          const numberKey = parseInt(key);
          // priority가 temp와 같은 경우 0으로 설정 ( 기존에 다른 시간에 우선순위가 등록되어있으면 0으로 초기화)
          if (value.priority === temp) {
            acc[numberKey] = { ...value, priority: 0 };
          } else { //그것이 아니라면 value를 acc객체에 넣고 return 
            acc[numberKey] = value;
          }
          return acc;
        },
        {} as SelectedSlotType,
      );

      // 특정 key에 대해 priority를 설정
      if (updatedSelectedSlots[numberItemKey]) {
        updatedSelectedSlots[numberItemKey] = {
          ...updatedSelectedSlots[numberItemKey],
          priority: temp,
        };
      }

      return updatedSelectedSlots;
    });
```
## 🔹 스크린샷을 남겨주세요!
![스크린샷 2024-07-10 오전 2 46 10](https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/81609304/08344726-90a3-4cf6-a1fa-6b6e8b842beb)

https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/81609304/f9a9d6d0-2735-4848-9df8-42fc49a1fa09

2024-07-10 13:33 UTC, simeunseo requested changes
정말 고생많으셨습니다...! 디버깅이 쉽지 않았을텐데...
근데 중간에 develop머지해서 제 커밋이 섞여들어간건가요?
develop을 바라보는 PR인데 왜 files changed에 포함되는거지...
그리고 conflict 나는 부분이 제 코드랑 관련된 내용이라서 제가 resolve했습니다!

2024-07-10 13:33 UTC, simeunseo commented on src/pages/selectSchedule/components/selectPriority/PriorityColumn.tsx
>    const getPriorityColumntyle = (selectedEntryId?: number, priority?: number) => {
여기는 제가 작성한 코드이긴 한데, priority가 undefined인 경우는 없어서 다음과 같이 바꿔주시겠어요? 🙏
그리고 이제보니 함수명이 getPriorityColumnStyle이 되어야하는데 오타가났네요..ㅎㅎ 이것도 같이 바꿔주시면 감사하겠습니다

```suggestion
  const getPriorityColumnStyle = (priority:number, selectedEntryId?: number) => {
```

2024-07-10 13:33 UTC, simeunseo commented on src/pages/selectSchedule/components/selectPriority/PriorityColumn.tsx
>              slotStyle={getPriorityColumntyle(selectedEntryId, priority)}
위에서 언급한 변경사항에 맞게 여기도 이렇게 고쳐주시면 되겠습니다!!

```suggestion
            slotStyle={getPriorityColumnStyle(priority, selectedEntryId)}
```

2024-07-10 13:33 UTC, simeunseo commented on src/pages/selectSchedule/components/selectPriority/PriorityColumn.tsx
> +        throw Error(`올바르지않은 priority ${priority}`);
priority가 올바르지 않은 경우는 잘 없겠지만, 만약에 이상한 값이 들어온다면 priority를 0으로 인식하는게 맞다고 생각이 듭니다. priority가 1,2,3인 객체를 제외하면 나머지는 전부 0이어서요! 
그래서 Error를 던지는게 아니라 default는 0으로 반환하면 어떨까요?
```suggestion
      default:
        return 0;
```

2024-07-10 13:33 UTC, simeunseo commented on src/pages/selectSchedule/components/selectPriority/PriorityDropdown.tsx
>      });
혹시 여기서 temp가 의미하는 바가 무엇인지를 포함해서, 이 부분 로직에 대해 좀 설명해주실수있나요?

2024-07-11 08:21 UTC, simeunseo commented on src/pages/selectSchedule/components/selectPriority/PriorityDropdown.tsx
>      });
numberItemKey와 nemberKey의 네이밍이 좀 헷갈리는 것 같습니다!
제가 제대로 이해한게 맞다면, numberItemKey는 현재 드롭다운에서 옵션을 선택해서 우선순위를 적용하고자하는 객체의 key이고, numberKey는 prev에서 객체들을 순회하면서 가져오는 key인 것 같습니다. 
**numberKey를 numberPrevItemKey로 바꾸는 것이 어떨까요?
또한 temp도, 현재 유저가 바꾸려고 선택한 우선순위에 해당하는 값이니 selectedPriority와 같은 이름으로 바꾸면 좋을 것 같습니다.**

그리고 이와 관련해서, 제가 selectedSlots에서 key의 타입을 number로 지정해놓는 바람에 쓸데없이 parseInt가 필요해지는 상황들이 생기는 것 같습니다. 객체의 key는 문자열로 자동 변환되기 때문에 number타입으로 지정할 필요가 없는데 이 부분은 제가 실수를 했습니다💦 그래서 변수 네이밍만 좀 개선해주시고 key의 타입 관련해서는 제가 따로 리팩토링하겠습니다!!

추가로, 이번 문제가 객체를 entries로 다루는 로직때문에 발생한 사이드이펙트이기 때문에 개선이 필요하다고 느꼈습니다.
데이터 자료형을 다시 고민해봐야할 것 같아서, 간단한 문제는 아니기 때문에 제가 추후 리팩토링을 해보겠습니다!

2024-07-15 19:01 UTC, ljh0608 reviewed
대부분 반영했고 변수 네이밍은 조금 더 고민해보았습니다! 좋은 리뷰 감사합니다

2024-07-16 14:04 UTC, simeunseo commented on src/pages/selectSchedule/components/selectPriority/PriorityColumn.tsx
> +        throw Error(`올바르지않은 priority ${priority}`);
완전 이해했습니다~ 동의합니다!!

2024-07-16 14:04 UTC, simeunseo commented on src/pages/selectSchedule/components/selectPriority/PriorityDropdown.tsx
>      });
좋습니다 변경본 확인하였습니다!!!

2024-07-16 14:04 UTC, simeunseo approved these changes
고생 많으셨습니다!

2024-07-17 05:34 UTC, merged